channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip 
  - pip:
      - rpaframework
      - selenium
  - anaconda-client=1.11.2
  - anaconda-navigator=2.4.0
  - anaconda-project=0.11.1
  - attrs=23.2.0
  - backports.functools-lru-cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.12.2
  - boltons=23.0.0
  - brotlipy=0.7.0
  - cached-property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - chardet=3.0.4
  - charset-normalizer=2.0.4
  - click=8.1.7
  - clyent=1.2.2
  - colorama=0.4.6
  - comtypes=1.4.5
  - conda=23.7.4
  - conda-build=3.24.0
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.0.2
  - conda_package_streaming=0.7.0
  - conda-repo-cli=1.0.75
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - convertdate=2.4.0
  - cryptography=42.0.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.6.1
  - docutils=0.21.2
  - et-xmlfile=1.1.0
  - exceptiongroup=1.2.2
  - exchangelib=5.4.2
  - fastjsonschema=2.16.2
  - filelock=3.9.0
  - fire=0.4.0
  - fonttools=4.53.1
  - fpdf2=2.7.5
  - furl=2.1.3
  - future=0.18.3
  - glob2=0.7
  - graphviz=0.13.2
  - h11=0.14.0
  - hijri-converter=2.3.1
  - holidays=0.21.13
  - htmldocx=0.0.6
  - idna=3.4
  - importlib_metadata=8.2.0
  - isodate=0.6.1
  - java-access-bridge-wrapper=1.2.0
  - jinja2=3.1.2
  - jsonpatch=1.32
  - jsonpath-ng=1.6.1
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter_core=5.3.0
  - korean-lunar-calendar=0.3.1
  - libarchive-c=2.9
  - lxml=5.2.2
  - markupsafe=2.1.1
  - menuinst=1.4.19
  - more-itertools=10.3.0
  - mss=6.1.0
  - navigator-updater=0.4.0
  - nbformat=5.9.2
  - netsuitesdk=1.24.0
  - notifiers=1.3.3
  - O365=2.0.26
  - oauthlib=3.2.2
  - openpyxl=3.1.5
  - orderedmultidict=1.0.1
  - outcome=1.3.0.post0
  - packaging=24.1
  - pathlib=1.0.1
  - pdfminer.six=20221105
  - pendulum=2.1.2
  - pillow=10.4.0
  - pip=22.3.1
  - pkginfo=1.9.6
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - psutil=5.9.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.18.0
  - pyjwt=2.8.0
  - pymeeus=0.5.12
  - pynput-robocorp-fork=5.0.0
  - pyopenssl=24.2.1
  - pyotp=2.9.0
  - pypdf=3.17.4
  - pyperclip=1.9.0
  - pyqt5=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pyspnego=0.11.1
  - python-dateutil=2.8.2
  - python-docx=0.8.11
  - python-dotenv=1.0.1
  - pytz=2023.3.post1
  - pytz-deprecation-shim=0.1.0.post0
  - pytzdata=2020.1
  - pywin32=305.1
  - pywinauto=0.6.8
  - pyyaml=6.0
  - qtpy=2.2.0
  - requests=2.31.0
  - requests-file=2.1.0
  - requests_ntlm=1.3.0
  - requests-oauthlib=1.3.1
  - requests-toolbelt=1.0.0
  - robocorp-storage=1.0.4
  - robotframework=6.1.1
  - robotframework-pythonlibcore=4.4.1
  - robotframework-requests=0.9.7
  - robotframework-sapguilibrary=1.1
  - robotframework-seleniumlibrary=6.5.0
  - robotframework-seleniumtestability=2.1.0
  - rpaframework=28.6.1
  - rpaframework-core=11.3.2
  - rpaframework-pdf=7.3.2
  - rpaframework-windows=7.5.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel-yaml-conda=0.17.21
  - selenium=4.15.2
  - setuptools=65.6.3
  - simple-salesforce=1.12.6
  - sip=6.6.2
  - six=1.16.0
  - smartsheet-python-sdk=3.0.3
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.4
  - sspilib=0.1.0
  - stringcase=1.2.0
  - tenacity=8.5.0
  - termcolor=2.4.0
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - trio=0.26.0
  - trio-websocket=0.11.1
  - tweepy=3.10.0
  - typing_extensions=4.12.2
  - tzdata=2024.1
  - tzlocal=4.3.1
  - uiautomation=2.0.20
  - ujson=5.4.0
  - urllib3=1.26.16
  - validators=0.20.0
  - webdriver-manager=4.0.1
  - wheel=0.38.4
  - win-inet-pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.16.0
  - wsproto=1.2.0
  - xlrd=2.0.1
  - xlutils=2.0.0
  - xlwt=1.3.0
  - zeep=4.2.1
  - zipp=3.19.2
  - zstandard=0.19.0