name: base
channels:
  - conda-forge
dependencies:
  - python==3.12
  - pip==23.2.1
  - pendulum==2.1.2
  - setuptools==71.0.4
  - pip:
      - rpaframework==28.6.1
      - selenium==4.15.2
      - RPA
      - robocorp
      - chromedriver-py==114.0.5735.90
      - robotframework-seleniumlibrary==6.3.0
      - webdriver-manager==4.0.1
ignorefiles:
  - .gitignore
