name: base
channels:
  - defaults
dependencies:
  - anaconda-client=1.11.2
  - anaconda-navigator=2.4.0
  - anaconda-project=0.11.1
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.12.2
  - boltons=23.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - clyent=1.2.2
  - colorama=0.4.6
  - conda=23.7.4
  - conda-build=3.24.0
  - conda-content-trust=0.1.3
  - conda-pack=0.6.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - conda-repo-cli=1.0.75
  - conda-token=0.4.0
  - conda-verify=3.4.2
  - console_shortcut=0.1.1
  - defusedxml=0.7.1
  - filelock=3.9.0
  - freetype=2.12.1
  - future=0.18.3
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - icu=58.2
  - idna=3.4
  - jinja2=3.1.2
  - jpeg=9e
  - jsonpatch=1.32
  - jsonpointer=2.1
  - jsonschema=4.17.3
  - jupyter_core=5.3.0
  - krb5=1.20.1
  - lerc=3.0
  - libarchive=3.6.2
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - liblief=0.12.3
  - libpng=1.6.39
  - libpq=12.15
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - lz4-c=1.9.4
  - m2-msys2-runtime=2.5.0.17080.65c939c
  - m2-patch=2.7.5
  - markupsafe=2.1.1
  - menuinst=1.4.19
  - msys2-conda-epoch=20160418
  - navigator-updater=0.4.0
  - nbformat=5.9.2
  - openssl=3.0.11
  - pathlib=1.0.1
  - pcre=8.45
  - pip=22.3.1
  - pkginfo=1.9.6
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - ply=3.11
  - powershell_shortcut=0.0.1
  - psutil=5.9.0
  - py-lief=0.12.3
  - pycosat=0.6.4
  - pycparser=2.21
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-libarchive-c=2.9
  - pytz=2023.3.post1
  - pywin32=305
  - pyyaml=6.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtpy=2.2.0
  - qtwebkit=5.212
  - requests=2.31.0
  - requests-toolbelt=1.0.0
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - ruamel_yaml=0.17.21
  - setuptools=65.6.3
  - sip=6.6.2
  - six=1.16.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - ujson=5.4.0
  - urllib3=1.26.16
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - attrs==23.2.0
      - cached-property==1.5.2
      - chardet==3.0.4
      - click==8.1.7
      - comtypes==1.4.5
      - convertdate==2.4.0
      - cryptography==42.0.5
      - decorator==5.1.1
      - dnspython==2.6.1
      - docutils==0.21.2
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.2
      - exchangelib==5.4.2
      - fire==0.4.0
      - fonttools==4.53.1
      - fpdf2==2.7.5
      - furl==2.1.3
      - h11==0.14.0
      - hijri-converter==2.3.1
      - holidays==0.21.13
      - htmldocx==0.0.6
      - importlib-metadata==8.2.0
      - isodate==0.6.1
      - java-access-bridge-wrapper==1.2.0
      - jsonpath-ng==1.6.1
      - korean-lunar-calendar==0.3.1
      - lxml==5.2.2
      - more-itertools==10.3.0
      - mss==6.1.0
      - netsuitesdk==1.24.0
      - notifiers==1.3.3
      - o365==2.0.26
      - oauthlib==3.2.2
      - openpyxl==3.1.5
      - orderedmultidict==1.0.1
      - outcome==1.3.0.post0
      - packaging==24.1
      - pdfminer-six==20221105
      - pendulum==2.1.2
      - pillow==10.4.0
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pymeeus==0.5.12
      - pynput-robocorp-fork==5.0.0
      - pyopenssl==24.2.1
      - pyotp==2.9.0
      - pypdf==3.17.4
      - pyperclip==1.9.0
      - pyspnego==0.11.1
      - python-docx==0.8.11
      - python-dotenv==1.0.1
      - python-graphviz==0.13.2
      - pytz-deprecation-shim==0.1.0.post0
      - pytzdata==2020.1
      - pywinauto==0.6.8
      - requests-file==2.1.0
      - requests-ntlm==1.3.0
      - requests-oauthlib==1.3.1
      - robocorp-storage==1.0.4
      - robotframework==6.1.1
      - robotframework-pythonlibcore==4.4.1
      - robotframework-requests==0.9.7
      - robotframework-sapguilibrary==1.1
      - robotframework-seleniumlibrary==6.5.0
      - robotframework-seleniumtestability==2.1.0
      - rpaframework==28.6.1
      - rpaframework-core==11.3.2
      - rpaframework-pdf==7.3.2
      - rpaframework-windows==7.5.1
      - selenium==4.15.2
      - simple-salesforce==1.12.6
      - smartsheet-python-sdk==3.0.3
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - sspilib==0.1.0
      - stringcase==1.2.0
      - tenacity==8.5.0
      - termcolor==2.4.0
      - trio==0.26.0
      - trio-websocket==0.11.1
      - tweepy==3.10.0
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - tzlocal==4.3.1
      - uiautomation==2.0.20
      - validators==0.20.0
      - webdriver-manager==4.0.1
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xlrd==2.0.1
      - xlutils==2.0.0
      - xlwt==1.3.0
      - zeep==4.2.1
      - zipp==3.19.2
